version: '3.7'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_mysql_password
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - nextcloud_network

  db:
    image: mariadb
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_root_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_mysql_password
    volumes:
      - nextcloud_db:/var/lib/mysql
    networks:
      - nextcloud_network

  nginx:
    image: nginx:latest
    container_name: nextcloud_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextcloud
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    driver: bridge

volumes:
  nextcloud_data:
  nextcloud_db:
